//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduAx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public decimal ID_PERSON { get; set; }
        public string NAME_PERSON { get; set; }
        public string EMAIL_PERSON { get; set; }
        public string PASS_PERSON { get; set; }
        public string ROLE_PERSON { get; set; }
        public string AVATAR_PERSON { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        public virtual GROUP GROUP { get; set; }
    }
}
