//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduAx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_COURSE
    {
        public decimal ID_STUDENT { get; set; }
        public decimal ID_COURSE { get; set; }
        public decimal STGRADE_STUDENTCOURSE { get; set; }
        public decimal NDGRADE_STUDENTCOURSE { get; set; }
        public decimal RDGRADE_STUDENTCOURSE { get; set; }
        public decimal THGRADE_STUDENTCOURSE { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
