//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduAx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_GROUP
    {
        public decimal ID_STUDENT { get; set; }
        public decimal ID_GROUP { get; set; }
        public Nullable<decimal> PLACES_STUDENTGROUP { get; set; }
    
        public virtual GROUP GROUP { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
