//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduAx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER
    {
        public decimal ID_TCH { get; set; }
        public decimal ID_TEACHER { get; set; }
        public decimal ID_GROUP { get; set; }
    
        public virtual GROUP GROUP { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
